apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.deploy.port }}
  selector:
    app: {{ .Values.deploy.labels.app }}
    tier: {{ .Values.deploy.labels.tier }}
  type: {{ .Values.service.type }}