apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.accessModes }}
  storageClassName: {{ .Values.pv.storageClassName }}
  claimRef:
   namespace: {{ .Values.pv.namespace }}
   name: {{ .Values.pv.pvcname }}
  hostPath:
    path: {{ .Values.pv.path }}
---
